# Generated by Django 5.1 on 2024-08-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blood_donation1_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sushant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablets', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
